services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: legaldoc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legaldoc_db
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=["http://localhost:3001","http://localhost:3000"]
      - ALLOWED_HOSTS=["*"]
      # All other environment variables are loaded from .env file
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (React)
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8001
        - REACT_APP_NAME=LegalDoc
        - REACT_APP_VERSION=2.0.0
        - REACT_APP_DESCRIPTION=AI-powered legal document analysis
        - GENERATE_SOURCEMAP=false
        - REACT_APP_DEBUG=false
        - REACT_APP_ENABLE_LAZY_LOADING=true
        - REACT_APP_CACHE_DURATION=300000
        - REACT_APP_ENABLE_CHAT_HISTORY=true
        - REACT_APP_ENABLE_DOCUMENT_EXPORT=true
        - REACT_APP_ENABLE_ADMIN_PANEL=true
        - REACT_APP_AUTH0_DOMAIN=dev-8oivjmih178u6qpg.us.auth0.com
        - REACT_APP_AUTH0_CLIENT_ID=USWlBGBM57kpWY8L5g1BTwYZ2uUArTAF
        - REACT_APP_AUTH0_AUDIENCE=https://legaldoc-api
        - REACT_APP_AUTH0_REDIRECT_URI=http://localhost:3001/callback
    ports:
      - "3001:80"
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - NODE_ENV=production
      # Auth0 environment variables loaded from .env file
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
      - REACT_APP_AUTH0_REDIRECT_URI=${REACT_APP_AUTH0_REDIRECT_URI}

volumes:
  postgres_data:
  redis_data:
